### ISSUE TITLE
"View Source" option no longer showing with most recent Android documentation.

### ISSUE THREAD

**Issue by stabib** [romannurik/AndroidSDKSearchExtension#23] opened 2016-05-17 17:22 UTC
I was using the extension today, and I noticed that the "View Source" option no longer shows up with the latest documentation redesign. I attached a screenshot:

<img width="1440" alt="screen shot 2016-05-17 at 10 18 46 am" src="https://cloud.githubusercontent.com/assets/1947297/15332101/224608c2-1c19-11e6-868b-27fc33b6c358.png">

**Comment by romannurik** [comment] 2016-05-17 18:20
Duplicate of #21

**Closed by romannurik** 2016-05-17 18:20 UTC
