### ISSUE TITLE
GCM reference URL breaks the extension

### ISSUE THREAD

**Issue by ming13** [romannurik/AndroidSDKSearchExtension#11] opened 2015-05-29 08:36 UTC
It seems like the `https://developer.android.com/reference/gcm_lists.js` doesn’t exist anymore.

```
$ http --verbose GET https://developer.android.com/reference/gcm_lists.js
GET /reference/gcm_lists.js HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: developer.android.com
User-Agent: HTTPie/0.9.2

HTTP/1.1 404 Not Found
Alternate-Protocol: 443:quic,p=1
Cache-Control: no-cache
Content-Length: 112
Content-Type: text/html; charset=utf-8
Date: Fri, 29 May 2015 08:17:29 GMT
Expires: Fri, 01 Jan 1990 00:00:00 GMT
Server: Google Frontend

<html><head><title>404: Not Found</title></head><body><b><h2>Error 404</h2><br/>File not found</b></body></html>
```

Probably it was moved somewhere to `https://developers.google.com/android/reference/packages`, but there are no reference JS files as far as I can see.

Unfortunately it breaks the extension itself and there is an infinite “Loading Android SDK search data…” sign at the omnibox.

**Comment by romannurik** [comment] 2015-06-01 14:00
Duplicate of #12

**Closed by romannurik** 2015-06-01 14:00 UTC
Labels: duplicate
